@baseURL = http://localhost:4000/api
@nome = Harry Potter e a Pedra Filosofal
//@nome = Anne de Avonlea

###
// GET - listar todos livros
GET {{baseURL}}/livros
Content-Type: application/json

###
//GET lista apenas um livro pelo nome ou mais de um pelo autor
GET {{baseURL}}/livros/{{nome}}
Content-Type: application/json


###
//POST - Inclui um novo livro
POST {{baseURL}}/livros
Content-Type: application/json

{
    "nome": "Anne de Avonlea" , 
    "autor": "Montgomery", 
    "paginas": 288, 
    "sinopse": "Agora com 16 anos, sentindo-se quase adulta, Anne está prestes a começar a lecionar na escola de Avonlea", 
    "preco": 8.68
}

###
//PUT - altera dados 
PUT {{baseURL}}/livros
Content-Type: application/json

{
    "nome": "Anne de Avonlea", 
    "autor": "Montgomery", 
    "paginas": 290, 
    "sinopse": "Agora com 16 anos, sentindo-se quase adulta, Anne está prestes a começar a lecionar na escola de Avonlea", 
    "preco": 9.39
}

###
//DELETE 
DELETE {{baseURL}}/livros/{{nome}}
Content-Type: application/json

